spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:sample;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
application:
  security:
    jwt:
      issuer: my-system
      audience: my-client
      expiration: 60
      refresh-token:
        expiration: 300

logging:
 level:
   root:
     com.example: DEBUG
     org.apache.catalina: DEBUG
